### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by studsch** [studsch/cool-app#133]

**Comment by tim8842** [comment]
![Image](https://github.com/studsch/cool-app/assets/79981959/bc01cc7f-9817-45c8-b8df-89233a451f75)



![Image](https://github.com/studsch/cool-app/assets/79981959/5e0192f0-0571-4ed0-be1a-6da4d8045412)



![Image](https://github.com/studsch/cool-app/assets/79981959/3be77ed4-8e33-4ef0-a6c9-d1dafc71e99f)

**Comment by tim8842** [comment]
нужно будет через дс вставлять либо кнопку
