### ISSUE TITLE
Разработать страницу поиска

### ISSUE THREAD

**Issue by studsch** [studsch/cool-app#17]

**Comment by tim8842** [comment]
Поиск людей
![image](https://github.com/studsch/cool-app/assets/79981959/de7e2e1f-0e73-4241-b63d-3ff7b1afc9ce)
Поиск постов
![image](https://github.com/studsch/cool-app/assets/79981959/c2f7c169-019a-4c06-83a6-5e7143578d14)
Минипоиск при нажатии на него
![image](https://github.com/studsch/cool-app/assets/79981959/78c84d6c-cbbc-4824-954b-aab7c318b407)
Минипоиск при вводе запроса
![image](https://github.com/studsch/cool-app/assets/79981959/1578c0b0-3ff5-48ca-8fd6-d56374b715a8)
