### ISSUE TITLE
Как будет выглядеть просмотр истории?

### ISSUE THREAD

**Issue by studsch** [studsch/cool-app#8]

**Comment by tim8842** [comment]
Вот так, сделал дизайна просмотра историй
![image](https://github.com/studsch/cool-app/assets/79981959/58f924b8-a887-4696-8210-e9666cb0db8f)

**Comment by tim8842** [comment]
Забыл добавить полоску сверху

**Comment by tim8842** [comment]
![image](https://github.com/studsch/cool-app/assets/79981959/75aae80a-886d-4827-8cf6-daa96fb2c66d)
доделал
